version = 1
SPDX-PackageName = "sql-query-analyzer"
SPDX-PackageSupplier = "RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/RAprogramm/sql-query-analyzer"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-License-Identifier = "MIT"
