# SPDX-FileCopyrightText: 2025 RAprogramm
# SPDX-License-Identifier: MIT

name: Clippy

on:
  workflow_call:
    inputs:
      rust_changed:
        required: true
        type: string

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    if: inputs.rust_changed == 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-targets --all-features -- -D warnings
